# Generated by Django 5.0.6 on 2026-08-17 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Rwandan phone number: 10 digits starting with 07 (e.g. 0788123456).', regex='^07[0-9]{8}$')]),
        ),
    ]
