# Generated by Django 5.0.6 on 2026-08-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('bishop_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dioceses/logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('location', models.CharField(blank=True, help_text='Sector/Cell/Village', max_length=200)),
                ('parish_pastor', models.CharField(blank=True, max_length=200)),
                ('service_times', models.TextField(blank=True, help_text='e.g. Sunday 8:00 AM & 10:30 AM')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parishes/photos/')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='dioceses.diocese')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('diocese', 'slug')},
            },
        ),
    ]
