# Generated by Django 5.0.6 on 2026-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='archdeacon_name',
            field=models.CharField(blank=True, help_text="The Venerable/Archdeacon overseeing this parish's archdeaconry", max_length=200),
        ),
        migrations.AddField(
            model_name='parish',
            name='archdeaconry',
            field=models.CharField(blank=True, help_text="e.g. 'Byumba Archdeaconry' - the group of parishes this one belongs to", max_length=200),
        ),
    ]
