# Generated by Django 5.0.6 on 2026-08-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0002_parish_archdeacon_name_parish_archdeaconry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('BISHOP', 'Bishop'), ('ARCHDEACON', 'Archdeacon'), ('PARISH_PASTOR', 'Parish Pastor'), ('ASSISTANT_PASTOR', 'Assistant Pastor'), ('DEACON', 'Deacon'), ('EVANGELIST', 'Evangelist'), ('OTHER', 'Other')], max_length=20)),
                ('archdeaconry', models.CharField(blank=True, help_text='For Archdeacons, or pastors tied to one', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clergy/photos/')),
                ('notes', models.TextField(blank=True)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clergy', to='dioceses.diocese')),
                ('parish', models.ForeignKey(blank=True, help_text='Leave blank for diocese-wide roles like Bishop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clergy', to='dioceses.parish')),
            ],
            options={
                'verbose_name_plural': 'Clergy',
                'ordering': ['level', 'name'],
            },
        ),
    ]
