# Generated by Django 5.0.6 on 2026-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0003_clergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Wide photo of the church building, used as the homepage background', null=True, upload_to='dioceses/covers/'),
        ),
    ]
