# Generated by Django 5.0.6 on 2026-08-17 08:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0004_diocese_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clergy/photos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Wide photo of the church building, used as the homepage background', null=True, upload_to='dioceses/covers/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dioceses/logos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='parish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parishes/photos/', validators=[core.validators.validate_image_file]),
        ),
    ]
