# Generated by Django 5.0.6 on 2026-08-17 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0005_alter_clergy_photo_alter_diocese_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Rwandan phone number: 10 digits starting with 07 (e.g. 0788123456).', regex='^07[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Rwandan phone number: 10 digits starting with 07 (e.g. 0788123456).', regex='^07[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='parish',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Rwandan phone number: 10 digits starting with 07 (e.g. 0788123456).', regex='^07[0-9]{8}$')]),
        ),
    ]
