# Generated by Django 5.0.6 on 2026-08-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0006_alter_clergy_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='intego_theme',
            field=models.CharField(blank=True, help_text="The year's theme/motto, e.g. 'Kwizera n'Ubwiyunge' (Faith and Reconciliation)", max_length=300),
        ),
        migrations.AddField(
            model_name='diocese',
            name='intego_verse_reference',
            field=models.CharField(blank=True, help_text="e.g. 'Yohana 3:16' or 'John 3:16'", max_length=100),
        ),
        migrations.AddField(
            model_name='diocese',
            name='intego_verse_text',
            field=models.TextField(blank=True, help_text='The full text of the guiding verse'),
        ),
        migrations.AddField(
            model_name='diocese',
            name='intego_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 2026', null=True),
        ),
    ]
