# Generated by Django 5.0.6 on 2026-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0007_diocese_intego_theme_diocese_intego_verse_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='diocese',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='diocese',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
