# Generated by Django 5.0.6 on 2026-08-14 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('dioceses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rwf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('TITHE', 'Tithe'), ('OFFERING', 'General offering'), ('BUILDING_FUND', 'Building fund'), ('GROUP_CONTRIBUTION', 'Group/union contribution'), ('OTHER', 'Other')], default='OFFERING', max_length=25)),
                ('method', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='MoMo/bank ref number, if any', max_length=100)),
                ('date_given', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.group')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_logged', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='dioceses.parish')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
    ]
