# Generated by Django 5.0.6 on 2026-08-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceses', '0006_alter_clergy_contact_phone_and_more'),
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('target_amount_rwf', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('momo_code', models.CharField(blank=True, help_text='MTN MoMo Pay code', max_length=50)),
                ('airtel_code', models.CharField(blank=True, help_text='Airtel Money code', max_length=50)),
                ('bank_details', models.CharField(blank=True, help_text='Bank name + account number', max_length=250)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='dioceses.diocese')),
                ('parish', models.ForeignKey(blank=True, help_text='Leave blank for a diocese-wide campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='dioceses.parish')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='offering',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Link this contribution to a specific fundraising campaign, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='offerings.campaign'),
        ),
    ]
