# Generated by Django 5.0.6 on 2026-08-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioceses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('MOTHERS_UNION', "Mothers' Union"), ('FATHERS_UNION', "Fathers' Union"), ('YOUTH_UNION', 'Youth Union'), ('CHOIR', 'Amatorero (Choir)'), ('CHILDREN', 'Children / Sunday School'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(help_text="Display name, e.g. 'Byumba Youth Union'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('leader_name', models.CharField(blank=True, max_length=200)),
                ('leader_contact', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='groups/photos/')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='dioceses.parish')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250)),
                ('title_rw', models.CharField(blank=True, max_length=250)),
                ('description_en', models.TextField(blank=True)),
                ('description_rw', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=250)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dioceses.parish')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.group')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=250)),
                ('title_rw', models.CharField(blank=True, max_length=250)),
                ('body_en', models.TextField()),
                ('body_rw', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='dioceses.diocese')),
                ('parish', models.ForeignKey(blank=True, help_text='Leave blank for a diocese-wide announcement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='dioceses.parish')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='content.group')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
