# Generated by Django 5.0.6 on 2026-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('MOTHERS_UNION', "Mothers' Union"), ('FATHERS_UNION', "Fathers' Union"), ('YOUTH_UNION', 'Youth Union'), ('CHOIR', 'Amatorero (Choir)'), ('CHILDREN', 'Children / Sunday School'), ('GFS', "Girls' Friendly Society (GFS)"), ('OTHER', 'Other')], max_length=20),
        ),
    ]
