# Generated by Django 5.0.6 on 2026-08-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_groupmember_groupphoto_song'),
        ('dioceses', '0003_clergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('preacher_name', models.CharField(blank=True, max_length=200)),
                ('date_preached', models.DateField()),
                ('scripture_reference', models.CharField(blank=True, help_text='e.g. John 3:16-21', max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='dioceses.diocese')),
                ('parish', models.ForeignKey(blank=True, help_text='Leave blank for a diocese-wide sermon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='dioceses.parish')),
            ],
            options={
                'ordering': ['-date_preached'],
            },
        ),
    ]
