# Generated by Django 5.0.6 on 2026-08-17 08:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/photos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='image',
            field=models.ImageField(upload_to='groups/gallery/', validators=[core.validators.validate_image_file]),
        ),
    ]
